sudo: required

language: python

services:
  - docker

matrix:
  include:
  - env: DATA_SOURCE=gb

script:
  - ./python/resolver_publicdns.py --database ./working/resolvers.db --publicdns $DATA_SOURCE
  - make build_eidolon
