exclude = [
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".git"
]

# Match black
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
extend-select = [
    "D",   # pydocstyle
    "F",   # flake8
    "I",   # isort
    "UP",  # pyupgrade
]

ignore = [
    "D203",  # incompatible with D211
    "D213",  # incompatible with D212
    "D400",
    "D401",
    "D415"
]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
