name: Cleanup

on:
  schedule:
    - cron: "47 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1
        with:
          # Must match the tag families in tags.json
          packages: eidolon/gb,eidolon/us,eidolon/global
          # 4 weeks of weekly publishes
          keep-n-tagged: 4
